---
- name: Backup RouterOS Devices to file
  hosts: mtk1
  gather_facts: false
  strategy: free
  vars:
# I recommend setting the timeout to two minutes or even longer depending on how long it takes the device to pull the file.
    ansible_command_timeout: 120
    ansible_ssh_user: ansible

  roles:
    - mtk-ros-backup
