---
# handlers file for mtk-ros-backup
  - name: email diffs
    mail:
      from: "{{ from_email }}"
      to: "{{ email_addresses }}"
      subject: Diff report for {{ inventory_hostname }}
      subtype: html
      host: "{{ smtp_server }}"
      attach: /diff_directory/{{ inventory_hostname }}_{{ current_date }}.html
    delegate_to: localhost
    when: diff_result.rc != 0

  # - name: remove temp files
  #   file:
  #     state: absent
  #     path: "/tmp/{{ inventory_hostname }}_{{ current_date }}.html"
  #   delegate_to: localhost
  #   listen: email diffs