---
# handlers file for mtk-ros-backup

- name: email diffs
  mail:
    from: "{{ from_email }}"
    to: "{{ email_addresses }}"
    subject: Diff report for {{ inventory_hostname }}
    subtype: html
    host: "{{ smtp_server }}"
    port: "{{ smtp_server_port }}"
    username: "{{ smtp_username }}"
    password: "{{ smtp_password }}"
    attach: /{{ diff_directory }}/{{ inventory_hostname }}_{{ current_date }}.html
  delegate_to: localhost
  when:
    - smtp_server is defined
    - smtp_username is defined
    - smtp_password is defined
    - diff_result.rc != 0

- name: email diffs
  mail:
    from: "{{ from_email }}"
    to: "{{ email_addresses }}"
    subject: Diff report for {{ inventory_hostname }}
    subtype: html
    host: "{{ smtp_server }}"
    port: "{{ smtp_server_port }}"
    attach: /{{ diff_directory }}/{{ inventory_hostname }}_{{ current_date }}.html
  delegate_to: localhost
  when:
    - smtp_server is defined
    - smtp_username is not defined
    - smtp_password is not defined
    - diff_result.rc != 0
# - name: remove temp files
#   file:
#     state: absent
#     path: "/tmp/{{ inventory_hostname }}_{{ current_date }}.html"
#   delegate_to: localhost
#   listen: email diffs
